# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{s3bear}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Cranston"]
  s.date = %q{2010-12-30}
  s.description = %q{S3Bear adds a url field to your models and will download remote files for paperclip to use}
  s.email = %q{cracell@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controller/s3_bear_uploads_controller.rb",
    "config/routes.rb",
    "flex_src/bin-release/flex-config.xml",
    "flex_src/compile",
    "flex_src/src/Globals.as",
    "flex_src/src/S3Uploader.as",
    "flex_src/src/com/adobe/net/MimeTypeMap.as",
    "flex_src/src/com/elctech/S3UploadOptions.as",
    "flex_src/src/com/elctech/S3UploadRequest.as",
    "flex_src/src/com/nathancolgate/s3_swf_upload/BrowseButton.as",
    "flex_src/src/com/nathancolgate/s3_swf_upload/S3Queue.as",
    "flex_src/src/com/nathancolgate/s3_swf_upload/S3Signature.as",
    "flex_src/src/com/nathancolgate/s3_swf_upload/S3Upload.as",
    "lib/railtie.rb",
    "lib/signature.rb",
    "lib/tasks/s3_bear.rake",
    "public/javascripts/jquery-1.4.4.min.js",
    "public/javascripts/jquery.html5_upload.js",
    "public/javascripts/postmessage.js",
    "public/upload.html",
    "test/helper.rb",
    "test/test_s3_bear.rb"
  ]
  s.homepage = %q{http://github.com/cracell/s3bear}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{S3Bear helps you upload files right to S3}
  s.test_files = [
    "test/helper.rb",
    "test/test_s3_bear.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, ["~> 0.6"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<aws-s3>, ["~> 0.6"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<aws-s3>, ["~> 0.6"])
  end
end

